In [56]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [57]:
tiny = pd.read_csv("tinydata.csv", index_col=0)
le = LabelEncoder()
tiny['Acceptance'] = le.fit_transform( tiny['Acceptance'] )
X = tiny.drop('Acceptance', axis=1)
y = tiny['Acceptance']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=2, random_state=25, stratify=y)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4, 2), (4,), (2, 2), (2,))

In [58]:
tf.random.set_seed(25)
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(2,)),
    tf.keras.layers.Dense(2),
    tf.keras.layers.Dense(1, activation='sigmoid')])
model.compile(loss='binary_crossentropy', metrics=['acc'], optimizer=tf.keras.optimizers.SGD())

In [59]:
model.get_weights()

[array([[0.28939784, 0.15367246],
        [0.17133331, 0.76312697]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.58293104],
        [ 1.2400371 ]], dtype=float32),
 array([0.], dtype=float32)]

In [60]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_22 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),verbose=2,epochs=100)

Epoch 1/100
1/1 - 1s - 638ms/step - acc: 0.5000 - loss: 0.6727 - val_acc: 0.5000 - val_loss: 0.5728
Epoch 2/100
1/1 - 0s - 82ms/step - acc: 0.5000 - loss: 0.6723 - val_acc: 0.5000 - val_loss: 0.5725
Epoch 3/100
1/1 - 0s - 81ms/step - acc: 0.5000 - loss: 0.6719 - val_acc: 0.5000 - val_loss: 0.5722
Epoch 4/100
1/1 - 0s - 82ms/step - acc: 0.5000 - loss: 0.6715 - val_acc: 0.5000 - val_loss: 0.5720
Epoch 5/100
1/1 - 0s - 93ms/step - acc: 0.5000 - loss: 0.6711 - val_acc: 0.5000 - val_loss: 0.5717
Epoch 6/100
1/1 - 0s - 80ms/step - acc: 0.5000 - loss: 0.6707 - val_acc: 0.5000 - val_loss: 0.5714
Epoch 7/100
1/1 - 0s - 80ms/step - acc: 0.5000 - loss: 0.6703 - val_acc: 0.5000 - val_loss: 0.5712
Epoch 8/100
1/1 - 0s - 87ms/step - acc: 0.5000 - loss: 0.6699 - val_acc: 0.5000 - val_loss: 0.5709
Epoch 9/100
1/1 - 0s - 82ms/step - acc: 0.5000 - loss: 0.6696 - val_acc: 0.5000 - val_loss: 0.5707
Epoch 10/100
1/1 - 0s - 81ms/step - acc: 0.5000 - loss: 0.6692 - val_acc: 0.5000 - val_loss: 0.5704
Epoch 11

In [62]:
model.get_weights()

[array([[0.28710774, 0.1585555 ],
        [0.16840664, 0.7693774 ]], dtype=float32),
 array([ 0.05082991, -0.10811616], dtype=float32),
 array([[-0.5831387],
        [ 1.249145 ]], dtype=float32),
 array([-0.08710093], dtype=float32)]

In [63]:
y_pred_prob = model.predict(X_test)
y_pred = np.where(y_pred_prob > 0.5, 1, 0)
accuracy_score(y_test, y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


1.0